apiVersion: apps/v1
kind: Deployment
metadata:
  name: betting-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: betting-api
  template:
    metadata:
      labels:
        app: betting-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: betting-api
          image: ghcr.io/thranox/betting-api:d1451754d80888ade6bbbdeca69446b85bc4e4c1
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi

