apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "70.4.2"
    helm:
      values: |
        prometheusOperator:
          admissionWebhooks:                                                                                                                                                                                                                   
            patch:
              enabled: false
          nodeSelector:
            kubernetes.io/hostname: ubuntu-4gb-nbg1-2
        kube-state-metrics:
          nodeSelector:
            kubernetes.io/hostname: ubuntu-4gb-nbg1-2
        alertmanager:
          alertmanagerSpec:
            nodeSelector:
              kubernetes.io/hostname: ubuntu-4gb-nbg1-2
        prometheus:
          prometheusSpec:
            nodeSelector:
              kubernetes.io/hostname: ubuntu-4gb-nbg1-2
        grafana:
          nodeSelector:
            kubernetes.io/hostname: ubuntu-4gb-nbg1-2
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            hosts:
              - grafana.thranox.com
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.thranox.com
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
