---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgCajWEhdezDIVyS0BhQ/sZnFL2rTnedztpA3J5X7gegLg5Dz/cSx0mbJ8x2Wi45fndEyfwPPJVXn5U31gnVKoDAkokC8MxiBKQ2YwT+Q4PdZHVnwuQOYoNe7jCnp+m65ByJhnVtL8mYvh6S9V2lZgp10+JC1lXd4x+JmDPdqs2xzSq3LmsYRaCGSqL85QyotdE7D1pkrwKGGeaNNkwtSBwZrECzmcV3mRTvlwfcZqyOc7HZlG1tLDUcfrDBmDSBYDa4OPIUPwDvERaAWCfJBsTQ1cHsKIZbDLdBXrNXnhfgMpZ956plL6SDCFQ0DvylISTS9nvQ8tXITnAV7JoumN0hxlgRku6/TghPrahmpnsodE1DZfX57/qqqf02kxh5gND6CHM9B4KRtcEnJ1R5Fpun6mKQqm7h3erZJbc//jDpAXjx1Gukvfe4uurZi3qBM7ulfQMOOoZ+hbKyhkKpZdVAfTaFWNVSqoeN5U88olvKpO/fdGXLOvwBMICbm4O/L5FjnxN1HQa0oucknKMlZ9pSySSBRHovbbnKFTemQez4FAHuXxWUA4+Yrl0tcwZLo/9nJewajdVdV7Rc5VvrGfdphFNXrKFCvYBdSyJD+jjRQYi5kNA2qf9Hy4OfBdfr9ePeMcEq9R8JnhYYJT7/RDYmcLIfeszonRORE+Urkt+DfmNBPaVyZcrKvvl5gQRw+I4iecj6tsrsBTkmiyZOzg==
  template:
    metadata:
      name: postgres-secret
      namespace: postgres
